/**
  ******************************************************************************
  * File Name          : Connect_Iot.c
  * Description        : This file provides code for the configuration
  *                      of Connect_Iot.
  ******************************************************************************
 */
  
/* Includes ------------------------------------------------------------------*/
#include "Connect_Iot_Task.h"
#include "ESP8266.h"
#include "UART_Printf.h"
#include "OLED.h"
/* External function declaration----------------------------------------------*/


/* Private macro definitions--------------------------------------------------*/


/* Global variable------------------------------------------------------------*/


/* Static function definition-------------------------------------------------*/

/* Function definition--------------------------------------------------------*/

/** 
* @description: Use at-MQTT instructions to connect ali Cloud platform 
* @param  {void} 
* @return {uint8_t } : if success,return (uint8_t)OPERATION_SUCCESS
* @author: leeqingshui 
*/
uint8_t Connct_aliyun_iot(void)
{
	printf("The Internet of Things cloud platform is connected\r\n");
	
	uint8_t ret = (uint8_t)OPERATION_SUCCESS;
	int connect_times = 0;
	
	/* Restore the factory default mode */
	if(ESP8266_AT_RESTORE() != (uint8_t)OPERATION_SUCCESS)
	{
		ret = (uint8_t)OPERATION_ERROR;
		return ret;
	}

	/* Set to client mode */
	if(ESP8266_Net_Mode_Choose(STA) != (uint8_t)OPERATION_SUCCESS)
	{
		ret = (uint8_t)OPERATION_ERROR;
		return ret;
	}
	
	/* Connect to a wireless network */
	while((!ESP8266_JoinAP(WIFI_NAME, WIFI_KEY)) && connect_times<10)
	{
		connect_times++;
		ret = ESP8266_JoinAP(WIFI_NAME, WIFI_KEY);
	}
	if(ret != (uint8_t)OPERATION_SUCCESS)
		return ret;
	connect_times = 0;
	
	/* Set the time domain and SNTP server */
	while((!ESP8266_Set_SNTP(8 , SNTP_SERVER_0 , SNTP_SERVER_1 , SNTP_SERVER_2)) && connect_times<10)
	{
		connect_times++;
		ret = ESP8266_Set_SNTP(8 , SNTP_SERVER_0 , SNTP_SERVER_1 , SNTP_SERVER_2);
	}
	if(ret != (uint8_t)OPERATION_SUCCESS)
		return ret;
	connect_times = 0;
	
	/* MQTT configures user attributes */
	if(ESP8266_MQTTUSERCFG( CLIENT_ID, MQTT_Username, MQTT_Password) != (uint8_t)OPERATION_SUCCESS)
	{
		ret = (uint8_t)OPERATION_ERROR;
		return ret;
	}
	
	/* Set the MQTT client ID : Generated by aliyun Iot platform configuration tool */
	if(ESP8266_MQTTSETCLIENTID(MQTT_User_client_id) != (uint8_t)OPERATION_SUCCESS)
	{
		ret = (uint8_t)OPERATION_ERROR;
		return ret;
	}
	
	/* Connect to the specified MQTT server */
	if(ESP8266_MQTTCONN( MQTT_Server_IP, MQTT_Server_PORT) != (uint8_t)OPERATION_SUCCESS)
	{
		ret = (uint8_t)OPERATION_ERROR;
		return ret;
	}
	
	printf("The cloud platform is successfully connected\r\n");
	
	return ret;
}





